import type { Metadata } from "next";
import Header from "@/components/Header";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const notoSansKr = Noto_Sans_KR({
  weight: ["500", "400", "300"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClass = `flex items-center w-full bg-white dark:bg-gray-950 justify-between py-10 ${notoSansKr.className}`;

  return (
    <html lang="ko">
      <body className={bodyClass}>
        <section className="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0">
          <Header />
          <main className="mb-auto">{children}</main>
        </section>
      </body>
    </html>
  );
}
